apiVersion: v1
kind: List
metadata:
  name: ibm-csi-block
  namespace: kube-system
  annotations:
    version: 1.4.0
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: "{{ namespace }}"
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: operatorgroup
      namespace: "{{ namespace }}"
    spec:
      targetNamespaces:
      - "{{ namespace }}"
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ibm-block-csi-operator
      namespace: "{{ namespace }}"
      labels:
        app.kubernetes.io/name: ibm-block-csi-operator
        app.kubernetes.io/instance: ibm-block-csi-operator
        app.kubernetes.io/managed-by: ibm-block-csi-operator
        release: ibm-block-csi-operator
    spec:
      channel: stable
      name: ibm-block-csi-operator
      source: certified-operators
      sourceNamespace: openshift-marketplace
      startingCSV: ibm-block-csi-operator.v1.4.0
      installPlanApproval: Automatic
