apiVersion: v1
kind: List
metadata:
  name: ibm-csi-block
  namespace: kube-system
  annotations:
    version: 1.4.0
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: "{{ namespace }}"
